# ===========================================
# File: config.yml
# Description: Rasa NLP pipeline & policies
# Optimized for a moderate medical/healthcare chatbot
# ===========================================
# ===========================================
# File: config.yml
# Rasa NLP pipeline & policies
# ===========================================

recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: "_"

- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer

- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5

- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  entity_recognition: true

- name: EntitySynonymMapper

- name: ResponseSelector
  epochs: 50
  constrain_similarities: true

- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

#- name: DucklingEntityExtractor
#  url: "http://localhost:8000"
#  dimensions:
#  - time
#  - number

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 7
  epochs: 100
  constrain_similarities: true
assistant_id: 20250923-165010-warm-octet
